spring.application.name=stock-pos
# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/stock_pos_db
spring.datasource.username=postgres
spring.datasource.password=san123
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
# spring.jpa.properties.hibernate.format_sql=true

# Security JWT
application.security.jwt.secret-key=MEU2MzUyNjY1NTZBNTg2RTMyNzIzNTczODdYMkY0MTNGNDQyODQ3MkI0QjYyNTA2NDUzNjc1NjZCNTk3MA==
#access-token expiration in 1 day
application.security.jwt.expiration=86400000
# refresh-token expiration in 7 days
application.security.jwt.refresh-token.expiration=604800000

